'use client'
import { useState } from 'react'
import { Sparkles, ArrowUpRight, Link2, Check, ArrowRight } from 'lucide-react'
import s from './continuity-home.module.css'
const examples = [
 {name:'Find an answer', question:'What does Sarah need to take over the weekly forecast?', answer:'In this example, Sarah needs the latest forecast workbook, the recurring meeting details and the decisions from the last review. Alex’s handoff brings those sources together with the responsibility to run the next call.', sources:['Relay handoff','SharePoint','Outlook'], detail:'Next step', action:'Review the workbook and meeting notes before the next forecast call.'},
 {name:'Find a gap', question:'What could interrupt Sarah’s handoff?', answer:'In this example, Sarah still needs access to the SharePoint workbook used for the weekly forecast. The handoff keeps that access issue visible for follow-up.', sources:['Access issue','SharePoint'], detail:'Access follow-up', action:'Ask the source administrator to confirm Sarah can open the workbook.'},
 {name:'Run a report', question:'Which handoffs need attention this week?', answer:'In this example, Alex’s handoff has an access issue awaiting follow-up, while Priya’s vendor review still needs a recipient. The report brings both outstanding actions into view.', sources:['Alex’s handoff','Priya’s handoff'], detail:'Outstanding actions', action:'Confirm workbook access for Sarah and assign Priya’s vendor review.'},
]
export function AskRelay(){
 const [selected,setSelected]=useState(0);const ex=examples[selected]
 return <section id="ask-relay" className={`${s.wrap} ${s.section} ${s.askLayout}`}>
  <div><p className={s.eyebrow}><Sparkles size={16}/> Ask Relay AI</p><h2>Ask Relay AI.<br/><span>Find your next step.</span></h2><p className={s.sectionText}>Ask Relay AI about your handoffs and authorized sources. Find outstanding gaps and explore continuity data in plain language.</p><ul className={s.checkList}><li><Check size={17}/>AI answers grounded in available context</li><li><Check size={17}/>Natural-language reports you can save and pin</li><li><Check size={17}/>Linked sources, with access scoped to your role</li></ul><a className={s.textLink} href="#demo">See Ask Relay AI in a demo <ArrowUpRight size={17}/></a></div>
  <div className={s.askCard}><div className={s.cardTop}><span><Sparkles size={17}/>Ask Relay AI</span><span className={s.neutralPill}>Example answers</span></div><div className={s.askOptions} aria-label="Choose an Ask Relay example">{examples.map((e,i)=><button key={e.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{e.name}</button>)}</div><div className={s.answer} aria-live="polite" aria-atomic="true"><div className={s.question}>{ex.question}<ArrowRight size={17}/></div><div className={s.response}><Sparkles size={20}/><p>{ex.answer}</p></div><div style={{borderTop:"1px solid #dedfdc",borderBottom:"1px solid #dedfdc",padding:"20px 0",marginBottom:20}}><p style={{margin:"0 0 8px",fontSize:14,fontWeight:600,color:"#626963"}}>{ex.detail}</p><p style={{margin:0,fontSize:16,lineHeight:1.6}}>{ex.action}</p></div><div className={s.sources}>{ex.sources.map(source=><span key={source}><Link2 size={13}/>{source}</span>)}</div></div><p className={s.note}>Select a question to explore a sample answer. This preview uses illustrative data.</p></div>
 </section>
}
