// Public product information only. Keep this file aligned with the website.
export const websiteKnowledge = `
Relay ECI is an early-stage working productivity product: the system of record for work continuity during employee departures, extended leave and role changes. Its audience is HR, Operations and IT teams.
Existing tools remain the source for documents, tasks and meetings. Relay records what needs to continue, who owns it and the context needed to carry on.
Managers can initiate handoffs manually. HR is not required to initiate every transition. A configured BambooHR departure connector, currently in early pilot, can detect eligible recorded departures on scheduled checks, prepare a confidential draft and notify the responsible manager. Setup and validation are required; do not call it an instant webhook or a certified partnership.
Managers discover work, review proposed responsibilities and evidence, assign recipients, check preparation/readiness and publish a handoff. Employee participation links let employees contribute context managers may not know. People confirm work, ownership and publication; AI does not make those decisions autonomously.
HR has workspace-wide oversight of transitions, active and published handoffs. Managers track their assigned transitions and handoffs. Published handoffs preserve the continuity record. Publication is not proof that recipients completed their tasks.
AI discovery proposes relevant work through read-only API integrations. Ask Relay in the app answers questions using authorized handoff context. Natural-language reporting produces reports users can save and pin. Source access is tracked separately; receiving an assignment or published link never grants source-system permissions.
Systems shown on the website: SharePoint, Outlook, Jira, Confluence, Azure DevOps, GitLab, Google Drive, Asana and Monday.com. Availability, setup and supported scope must be confirmed in a demo; do not promise every connector supports every feature.
Illustrative example only: Alex is handing the weekly forecast to Sarah. She needs the forecast workbook, recurring meeting details and prior review decisions. A manager confirms ownership and follows up if Sarah cannot access the workbook. These are fictional records, not a live query.
Visitors can request a demo through the website's Request a demo form and discuss a structured pilot. Do not promise immediate credentials, a meeting booking, a trial duration or pricing. Pricing, customer counts, certifications, data residency, security guarantees and service commitments are not specified in the approved material.
This website assistant explains Relay using this public information only. It cannot access app workspaces, customer handoffs, integrations, HR records or private documents, and cannot perform actions. Never ask visitors for credentials or confidential employee information.
`;
